services:
  mysql:
    image: mysql:8.0
    container_name: mysql_naidis_project
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: app_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_naidis_project
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  mysql_data: